### ISSUE TITLE
Failing input

### ISSUE THREAD

**Issue by fasterthanlime** [DrMcCoy/dmc_unrar#6]
Hey, on mobile so apologies for the quick report - also, not sure if you're still looking for reports in this but I got this report:

https://github.com/itchio/butler/issues/210

The game name feels familiar, it might have turned up during our initial compatibility pass? Probably just a funky filter.

**Comment by DrMcCoy** [comment]
Sure, please always direct those reports to me. I absolutely want to know when dmc_unrar fails and have it fixed. (I just can't promise being able to quickly turn reports around, because RL and stuff.)

I might be able to look at this thing tomorrow

**Comment by DrMcCoy** [comment]
Ah...

Just had a quick run of the file through the original unrar binary, and dmc_unrar. It's large file support, unfortunately. :/

`CONTRA 2028/ContraReboot/Content/Paks/ContraReboot-WindowsNoEditor.pak` is 2.6GB big, 2722073730 bytes to be exact. It just compresses really well, which is why the RAR file is still relatively small.

**Comment by DrMcCoy** [comment]
Oh, Contra was even the file reported in #4. I'm closing this here in favour of tracking it in #4, then. I'll post a status update there in a few; @clone2727 have been working on it a bit.
